language: node_js
node_js:
  - "node"
  - "7"
  - "6"
  - "4"
sudo: false
git:
  depth: 10
branches:
  only:
    - master
script: "npm run-script test-ci"
after_script: "cat ./coverage/lcov.info | coveralls"
